#!/bin/sh

if [ $PROJECT_LOC ]; then
	sudo mkdir -p $PROJECT_LOC
	mount | grep -q $PROJECT_LOC
	if [ $? != 0 ]; then
		sudo mount --bind $EMBOX_DIR $PROJECT_LOC
	fi
fi

echo $$ > ~/gdbwrapper.pid

exec gdb "$@"
