#!/bin/bash

D=$(date '+%H:%M:%N')

mktmpfifo() {
	f=$(mktemp)
	rm $f
	mkfifo $f
	echo $f
}

FIFO=$(mktmpfifo)
CMD=$(mktemp)
cleanup() {
	rm -f $FIFO $CMD
}

trap 'cleanup' INT QUIT TERM EXIT

{ awk -v EMBOX_DIR=${EMBOX_DIR} -f /usr/local/share/miwrapper.awk <&3 3<&- > $FIFO & } 3<&0

# `script` tends to catch arguments to external command,
# so we make a little shell with command and parameters here
echo "gdb $@" > $CMD
chmod +x $CMD
script -qfc "$CMD" /dev/null < $FIFO
